Fix #10会計局財政総括を執筆
ritscc/soukai-2020-2 pull request #108
Opened 2021-02-18 11:36 UTC by Tanabe-616

2021-02-19 17:25 UTC, CityBear3 commented on src/soukatsu/kaikei/02_zaisei.tex
> +会費の合計としては¥202，500であった．
春学期総会では"¥"ではなく"円"のだったので変更した方がいいと思います

2021-02-19 17:58 UTC, CityBear3 commented on src/soukatsu/kaikei/02_zaisei.tex
>  %\writtenBy{\kaikeiStaff}{田邉}{雄士}
文責がコメントアウトをされていますが

2021-02-22 09:58 UTC, CityBear3 approved these changes

2021-02-23 08:08 UTC, kyochn commented on src/soukatsu/kaikei/02_zaisei.tex
> +会費の合計としては202，500円であった．
ここの「，」最早ない方がいいですね

2021-02-23 11:11 UTC, Tanabe-616 commented on src/soukatsu/kaikei/02_zaisei.tex
> +会費の合計としては202，500円であった．
遅くなって申し訳ないです.
修正しました.

2021-02-23 12:02 UTC, kyochn approved these changes

2021-02-24 12:59 UTC, 3to5thpower requested changes

2021-02-24 12:59 UTC, 3to5thpower commented on src/soukatsu/kaikei/02_zaisei.tex
> +\subsubsection*{予算}
予算の執行率がやばかった問題と昨年度の学術本部の任務懈怠の件が記述されてないのでよろしくお願いします

2021-02-25 08:12 UTC, Tanabe-616 commented on src/soukatsu/kaikei/02_zaisei.tex
> +\subsubsection*{予算}
財務総括の方で触れているんですがそれでは不十分ですか？

2021-02-25 11:37 UTC, tatsuya999 approved these changes

2021-02-25 11:37 UTC, merged