研究推進局全体総括を執筆
ritscc/soukai-2020-2 pull request #113
Opened 2021-02-19 16:55 UTC by ygkn

Fix #12

2021-02-21 12:13 UTC, thetaleisalsowhite approved these changes

2021-02-23 10:11 UTC, fukada6280 requested changes

2021-02-23 10:11 UTC, fukada6280 commented on src/soukatsu/kensui/01_zentai.tex
> +会員の活動が少なかったためと考えられる．
```
また，飛び込みLTも例年より大幅に減少していたが，対面での課外活動を自粛していたことにより，
会員の活動が少なかったことが原因と考えられる．
```
ため，ためと続いていたので以上のように変更したほうがいいと思います。

2021-02-23 10:15 UTC, fukada6280 approved these changes

2021-02-24 13:06 UTC, tatsuya999 approved these changes

2021-02-24 13:07 UTC, merged