soukatsu/zentai/03_project.tex:プロジェクト活動総括
ritscc/soukai-2020-2 pull request #114
Opened 2021-02-19 18:21 UTC by ygkn

Fixes #3

2021-02-19 18:51 UTC, averak approved these changes

2021-02-20 13:39 UTC, tatsuya999 commented on src/soukatsu/zentai/03_project.tex
> +かつ上回生会議でも確認を行っていなかったからである．
「行っていなかったため」の方が良いかも

2021-02-20 13:41 UTC, ygkn commented on src/soukatsu/zentai/03_project.tex
> +かつ上回生会議でも確認を行っていなかったからである．
なるほど〜〜〜〜〜〜〜〜〜〜

2021-02-20 13:45 UTC, ygkn commented on src/soukatsu/zentai/03_project.tex
> +かつ上回生会議でも確認を行っていなかったからである．
直したマン

2021-02-21 07:28 UTC, ygkn commented
本当になったので [WIP] 消した

2021-02-21 11:14 UTC, 3to5thpower approved these changes
問題はないとは思うんですけど全プロジェクトが通年になったことによる影響とかをどっかに書いといてほしい感もありますね…
後期に新しくプロジェクト立てたかったみたいな話もどっかで聞いた気がするので

2021-02-21 11:29 UTC, tatsuya999 approved these changes

2021-02-22 14:54 UTC, ygkn commented
> 問題はないとは思うんですけど全プロジェクトが通年になったことによる影響とかをどっかに書いといてほしい感もありますね…
> 後期に新しくプロジェクト立てたかったみたいな話もどっかで聞いた気がするので

たし🦀 そうですね
かいときます

2021-02-23 06:01 UTC, tatsuya999 approved these changes

2021-02-23 10:46 UTC, fukada6280 requested changes

2021-02-23 10:46 UTC, fukada6280 commented on src/soukatsu/zentai/03_project.tex
> +また，発表時間を10~20分に予め制限したいたため，長時間や短時間の発表は無かった．
したいた->していた

2021-02-23 11:10 UTC, ygkn commented on src/soukatsu/zentai/03_project.tex
> +また，発表時間を10~20分に予め制限したいたため，長時間や短時間の発表は無かった．
なんと！

2021-02-23 11:12 UTC, ygkn commented on src/soukatsu/zentai/03_project.tex
> +また，発表時間を10~20分に予め制限したいたため，長時間や短時間の発表は無かった．
なおしたマン

2021-02-24 12:50 UTC, merged