Fix #48:ブランチと改行
ritscc/soukai-2020-2 pull request #135
Opened 2021-02-21 16:56 UTC by RosesAndViolets

2021-02-22 06:29 UTC, kyochn commented on src/houshin/kensui/02_project.tex
> +本項では本局におけるプロジェクト活動業務に関する2020年度秋学期の方針を以下の点において述べる．
2020年度秋->2021年度春

2021-02-22 06:29 UTC, kyochn commented on src/houshin/kensui/02_project.tex
> +新規プロジェクト設立については，新型コロナウイルス感染症に対する大学の対応やリモート環境などの安定していない状況によって，活動の継続が困難になることを懸念して設立は認めない．
これ2020年度秋学期方針では？

2021-02-22 06:29 UTC, kyochn commented on src/houshin/kensui/02_project.tex
> +ある場合は，班内での活動計画を再考後，上回生会議にて提出を行う．
これも2020年度秋学期方針では

コピペするなら内容確認して貰っていいですか

2021-02-22 14:51 UTC, ygkn requested changes

2021-02-22 14:51 UTC, ygkn commented on src/houshin/kensui/02_project.tex
> +新規プロジェクト設立については，新型コロナウイルス感染症に対する大学の対応やリモート環境などの安定していない状況によって，活動の継続が困難になることを懸念して設立は認めない．
わかルマン

2021-02-22 14:51 UTC, ygkn commented on src/houshin/kensui/02_project.tex
> +ある場合は，班内での活動計画を再考後，上回生会議にて提出を行う．
わかルマン

2021-02-22 15:54 UTC, RosesAndViolets commented on src/houshin/kensui/02_project.tex
> +ある場合は，班内での活動計画を再考後，上回生会議にて提出を行う．
方針ノートの「会員のプロジェクト管理」のところが空で何を書けばいいのか分からないので，とりあえず今年に該当しそうな感じには修正しました．結局はコピペなんで全然ダメならどんな感じで書けばいいのか教えていただけると幸いです．

2021-02-22 22:22 UTC, kyochn approved these changes
見た感じ良さそう
詳しい内容の確認は研究推進局の方お願いします

2021-02-23 08:23 UTC, ygkn approved these changes
<img alt="LGTM" height="200" src="https://user-images.githubusercontent.com/14973783/108817730-b2af3500-75fb-11eb-8b28-78c0deb584fc.png" />

2021-02-23 08:23 UTC, ygkn commented on src/houshin/kensui/02_project.tex
> +ある場合は，班内での活動計画を再考後，上回生会議にて提出を行う．
これでOKよ

2021-02-23 10:49 UTC, fukada6280 approved these changes

2021-02-24 14:05 UTC, kyochn requested changes
WrittenByのところはStaffでお願いします

2021-02-25 12:02 UTC, kyochn approved these changes

2021-02-25 12:02 UTC, merged