Fix #49:ブランチと改行
ritscc/soukai-2020-2 pull request #136
Opened 2021-02-21 16:56 UTC by RosesAndViolets

2021-02-22 06:15 UTC, kyochn commented on src/houshin/kensui/03_LT.tex
> +2020年度秋学期は\firstGrade{}を中心にLTを行う．時間は正確に5分とし，内容に関しては2021年度も情報系に限定して行ってもらう．
7行目
方針か総括かわからんことになってるので内容の確認お願いします(多分soukai-2020-1からコピペして修正忘れてる感じかなと思うんですが)

2021-02-22 06:15 UTC, kyochn commented on src/houshin/kensui/03_LT.tex
> +受賞者には購入申請無しに本またはそれに相当するとみなせる物品を購入できる権利を与える．
「相当するとみなせる」は単に「相当する」でいいかも

2021-02-22 14:50 UTC, ygkn requested changes

2021-02-22 14:50 UTC, ygkn commented on src/houshin/kensui/03_LT.tex
> +2020年度秋学期は\firstGrade{}を中心にLTを行う．時間は正確に5分とし，内容に関しては2021年度も情報系に限定して行ってもらう．
```suggestion
2021年度春学期は\secondGrade{}を中心にLTを行う．時間は正確に5分とし，内容に関しては2021年度も情報系に限定して行ってもらう．
```

こうやね

2021-02-22 22:26 UTC, kyochn approved these changes

2021-02-23 08:27 UTC, ygkn approved these changes
https://github.com/ritscc/soukai-2020-2/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+review-requested%3A%40me

2021-02-23 10:50 UTC, fukada6280 approved these changes

2021-02-24 14:07 UTC, kyochn requested changes
ここもstaffでお願いします

2021-02-25 12:03 UTC, kyochn approved these changes

2021-02-25 12:03 UTC, merged