#16 アドカレ総括を執筆
ritscc/soukai-2020-2 pull request #140
Opened 2021-02-23 22:31 UTC by tsubopi

2021-02-24 03:21 UTC, averak approved these changes

2021-02-24 04:43 UTC, kanon-k4 commented on src/soukatsu/syogai/02_adcale.tex
>  \subsection*{アドカレ総括}
# 老害発言です
これの元となる、アドカレ方針はいつ、どこにあるのだろうか。

あと**「Advent Calendar総括」**で。

2021-02-24 06:16 UTC, kyochn commented on src/soukatsu/syogai/02_adcale.tex
>  \subsection*{アドカレ総括}
「アドカレ総括」はassignしたときの僕のミスですね
修正オナシャス

2021-02-24 06:30 UTC, kyochn requested changes
アドカレ総括->Advent Calendar総括

2021-02-24 06:31 UTC, kyochn reviewed
前回の方針がどういうものだったか箇条書きかなにかで冒頭にまとめたほうがいいです

2021-02-24 12:14 UTC, 3to5thpower commented on src/soukatsu/syogai/02_adcale.tex
>  \subsection*{アドカレ総括}
これはどっかの上回生会議でも言われてたんですが、渉外局が本来19年度秋学期に立てるべき方針を20年度春学期総会に先延ばしにし、その上立てるのを忘れたという事案なのでどうしようもないですね…
その旨と渉外局員が実際に従った方針を記述するなどしないと…

2021-02-25 11:49 UTC, kyochn approved these changes

2021-02-25 11:49 UTC, tatsuya999 approved these changes

2021-02-25 11:49 UTC, merged