[fix] 渉外局全体総括を執筆 fix #15
ritscc/soukai-2020-2 pull request #65
Opened 2021-02-14 09:30 UTC by averak

2021-02-19 15:25 UTC, 3to5thpower approved these changes

2021-02-19 17:15 UTC, lufeee approved these changes

2021-02-21 07:37 UTC, thetaleisalsowhite approved these changes

2021-02-24 13:12 UTC, 3to5thpower requested changes
コピペするにしても年度と学期くらい書き換えてください…

2021-02-24 13:12 UTC, tatsuya999 commented on src/soukatsu/syogai/01_zentai.tex
> +本局は，2020度春学期も2019度秋学期に引き続き以下の二つを目的として活動した．
一学期分ズレてないすか？

2021-02-24 13:12 UTC, tatsuya999 commented on src/soukatsu/syogai/01_zentai.tex
> +これを達成するため，以下の二つを2020度春学期の目標とした．
2020年度秋かな？

2021-02-24 14:41 UTC, tatsuya999 approved these changes

2021-02-24 14:43 UTC, 3to5thpower approved these changes

2021-02-24 14:45 UTC, 3to5thpower commented on src/soukatsu/syogai/01_zentai.tex
> +本局は，2021度春学期も2020度秋学期に引き続き以下の二つを目的として活動した．
「20年度秋も春に引き続き」では？

2021-02-24 14:55 UTC, merged