[add]　システム管理局サーバ管理方針を執筆 #57
ritscc/soukai-2020-2 pull request #79
Opened 2021-02-15 14:12 UTC by thetaleisalsowhite

2021-02-19 15:06 UTC, 3to5thpower commented on src/houshin/system/04_server.tex
> +立命館大学コンピュータクラブデータセンター(以下，RCCDCと表記する)とは本会における情報の保存を一括して行うことを目的としたストレージの呼称である．
RCCDC，RCCとDCの間にスペースとかハイフンとか入れないんですか？

2021-02-21 07:32 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +立命館大学コンピュータクラブデータセンター(以下，RCCDCと表記する)とは本会における情報の保存を一括して行うことを目的としたストレージの呼称である．
一単語と考えてハイフンで統一しました

2021-02-21 12:02 UTC, lufeee commented on src/houshin/system/04_server.tex
> +必要に応じて応じて各種依存環境の調査を行い，中長期的な視点で更新を行えるように対応する．
「必要に応じて」の「応じて」が２つあります．片方の消去お願いします

2021-02-21 12:40 UTC, kyochn commented on src/houshin/system/04_server.tex
> +現在において対応にあたり最も有用であると考えられるCent Streamの調査を行う．
「現在において対応にあたり」よりは「現在における対応のうち」の方が自然かと

2021-02-21 13:03 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +立命館大学コンピュータクラブデータセンター(以下，RCCDCと表記する)とは本会における情報の保存を一括して行うことを目的としたストレージの呼称である．
RCC Wikiに合わせてスペースにしました

2021-02-21 13:07 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +現在において対応にあたり最も有用であると考えられるCent Streamの調査を行う．
現時点で可能な対応のうち，
にしました

2021-02-21 13:14 UTC, kyochn commented on src/houshin/system/04_server.tex
> +現時点で可能な対応のうち，最も有用であると考えられるCent Streamの調査を行う．
「現時点での対応のうち，最も有用」なのは「Cent Stream」というより「Cent Streamに更新すること」なので
「現時点での対応のうち，更新先として最も有用である～」の方がいいかもしれませんね…

あと調査前なので「有用である」と断定するより「有用であると予想される」とかの方がいいですね

2021-02-21 13:34 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +立命館大学コンピュータクラブデータセンター(以下，RCCDCと表記する)とは本会における情報の保存を一括して行うことを目的としたストレージの呼称である．
やっぱりRCC Wikiと同様スペースにしました。

2021-02-21 13:34 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +現時点で可能な対応のうち，最も有用であると考えられるCent Streamの調査を行う．
なるほど！そうか！直します。

2021-02-21 13:42 UTC, kyochn approved these changes

2021-02-22 11:42 UTC, SAINE-TZ approved these changes
サーバー管理についてあまり存じ上げておりませんが、文章において特に異論はないです

2021-02-23 06:00 UTC, tatsuya999 approved these changes

2021-02-24 14:20 UTC, tatsuya999 commented on src/houshin/system/04_server.tex
> +\subsubsection*{立命館大学コンピュータクラブデータセンター}
大学いらないです

2021-02-24 14:22 UTC, kanon-k4 requested changes

2021-02-24 14:22 UTC, kanon-k4 commented on src/houshin/system/04_server.tex
> +\subsubsection*{立命館大学コンピュータクラブデータセンター}
**NASの運用** に訂正してください

2021-02-24 14:23 UTC, 3to5thpower commented on src/houshin/system/04_server.tex
> +\subsubsection*{立命館大学コンピュータクラブデータセンター}
ここのサブサブセクション名は変な固有名称使わないで「NASの運用」とかにしてください…

2021-02-24 15:36 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +\subsubsection*{立命館大学コンピュータクラブデータセンター}
変なて…直します

2021-02-24 16:22 UTC, thetaleisalsowhite commented on src/houshin/system/04_server.tex
> +\subsubsection*{NASの運用}
DCの設計and制作に関しての記述をすべしと事前の話し合いであった結果、言葉をこねくり回したのですが、文意はよろしいでしょうか。

2021-02-25 12:11 UTC, merged