Reopen #13 updated 02_project.tex
ritscc/soukai-2020-2 pull request #95
Opened 2021-02-16 09:16 UTC by Ta-2

2021-02-19 14:29 UTC, 3to5thpower commented on src/soukatsu/kensui/02_project.tex
> +2021年度秋学期の本局プロジェクト活動方針は，会員のプロジェクト活動を円滑に進行する為，進捗確認などのサポートを行うことであった．
2020年度では？

2021-02-19 14:30 UTC, 3to5thpower commented on src/soukatsu/kensui/02_project.tex
> +二つ目の問題については，週報の提出状況から班の継続不能な状況を察知し，研究推進局から事情を聴衆する必要があったと考えられた．
「聴衆」->「聴取」

2021-02-19 18:45 UTC, ygkn approved these changes

2021-02-19 18:45 UTC, ygkn commented on src/soukatsu/kensui/02_project.tex
> +一つ目の問題については，プロジェクト設立の際にリーダーの活動感想を見越した審査基準が必要と考えられた．例えば，リーダーのプロジェクト活動以外の仕事量を考慮するなど．
```suggestion
一つ目の問題については，プロジェクト設立の際にリーダーの活動感想を見越した審査基準が必要と考えられた．例えば，リーダーのプロジェクト活動以外の仕事量を考慮するなどである．
```

2021-02-19 18:46 UTC, ygkn requested changes
間違えた

2021-02-23 08:43 UTC, kyochn approved these changes

2021-02-23 08:51 UTC, ygkn approved these changes
<img alt="LGTM" height="200" src="https://user-images.githubusercontent.com/14973783/108817730-b2af3500-75fb-11eb-8b28-78c0deb584fc.png" />

2021-02-24 04:55 UTC, 3to5thpower approved these changes

2021-02-24 13:08 UTC, merged